name: upload_translized
on:
  push:
    branches:
      - 'main'


jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository
        uses: actions/checkout@v4

      - name: Upload to translized
        run: |
          ruby upload.rb false - -