name: upload_translized
on:
  push:
    branches:
      - 'main'
    paths:
      - 'languages/**'


jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository
        uses: actions/checkout@v4

      - name: Translized upload
        uses: translized/upload@v0.12
      # - uses: localazy/upload@v1

      # - name: Upload to translized
      #   run: |
      #     ruby upload.rb false - -